version: "3"
services:
  app:
    build: .
    ports:
      - 5000

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/nginx.conf:ro
        #- ./flaskblog:/etc/nginx/conf.d/default.conf:ro
    depends_on:
       - app
    ports:
       - "80:80"
